# Copyright (c) 2001 IBK-Landquart-Switzerland. All rights reserved.
#
# Module      :  Makefile
# Application :  IBK Open Class Library
# Purpose     :  Build all targets for IBM VisualAge C++
#
# Date        Description                                 Who
# --------------------------------------------------------------------------
# 2001.06.15  First implemention                          P.Koch, IBK
# 2001.06.29  Add MySQL                                   P.Koch, IBK
# 2001.07.10  Rename to CSL                               P.Koch, IBK
#
# OPEN SOURCE LICENSE
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to IBK at info@ibk-software.ch.

TARGETS = \
  Base.bld \
  Csl.bld \
  CslApi.bld \
  CslWrap.bld \
  CslExe.bld \
  Oracle.bld \
  Db2.bld \
  Mysql.bld \
  ComLib.bld \
  DaxLib.bld \
  FileLb.bld \
  MathLb.bld \
  PrfLib.bld \
  RexLib.bld \
  StrLib.bld \
  SysLib.bld

all : $(TARGETS)

$(TARGETS):
  !@echo ----------------------------------------------------------
  !@echo Build $*
  !@cd $*
  !@$(MAKE) /nologo
  !@cd ..

install : all
  @echo Installing csl kernel and libraries
  @copy bin\*.* ..\bin >nul

clean : $(TARGETS:.bld=.cln)

$(TARGETS:.bld=.cln) :
  !@echo Clean up $*
  !@cd $*
  !@$(MAKE) /nologo clean
  !@cd ..
