C Scripting Language (CSL) is a powerful and easy programming language available for Windows, OS/2 and unixish systems (Linux, FreeBSD, Solaris etc.). CSL follows the C syntax very closely and programmers used to C or C++ will immediately be familiar with it.

CSL is used like an interpreter: You write the program with your favorite editor and run it directly like any BAT, CMD, REXX or PERL script.

More than that, CSL can be integrated in applications as a macro language. CSL has 2 API sets: A "C" API for any 32 bit compiler, and C++ class interface for selected compilers.

By the DATA ACCESS LIBRARIES included in the base package, CSL is prepared also for high performance db tasks against Oracle, DB2, MySQL and ODBC sources: data import/export, schema setup scripts and further.

CSL is free software and open source under the GPL published by the Free Software Foundation.
