# Copyright (c) 2001 IBK-Landquart-Switzerland. All rights reserved.
#
# Module      :  Makefile
# Application :  IBK Open Class Library
# Purpose     :  Build Csl.exe
#
# Date        Description                                 Who
# --------------------------------------------------------------------------
# 2001.06.15  First implemention                          P.Koch, IBK
# 2001.07.10  Rename to CSL                               P.Koch, IBK
#
# OPEN SOURCE LICENSE
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to IBK at info@ibk-software.ch.

!include ..\location

TARGET     = Csl
SRCDIR     = $(SRCROOT)\CslExe
TARGETS    = $(IBINDIR)\$(TARGET).exe
TARGETDIRS = $(IBINDIR)
LIBRARIES  =
CLEANUPS   = $(TARGET).rc Csl.ico CslFile.ico
CDEFS      =
OBJECTS    = $(TARGET).obj
INCLUDES   =

!include ..\makeprog

Csl.ico : $(ICONDIR)\Csl.ico
  @echo copy to $@
  @copy $** $@ >nul

CslFile.ico : $(ICONDIR)\CslFile.ico
  @echo copy to $@
  @copy $** $@ >nul

$(TARGET).rc : Csl.ico CslFile.ico makefile
	@echo creating $@
	@echo ICON 1 Csl.ico > $@
	@echo ICON 2 CslFile.ico >> $@
