# Copyright (c) 2001 IBK-Landquart-Switzerland. All rights reserved.
#
# Module      :  Makefile
# Application :  IBK Open Class Library
# Purpose     :  Build ZOracleI.dll
#
# Date        Description                                 Who
# --------------------------------------------------------------------------
# 2001.06.09  First implemention                          P.Koch, IBK
#
# OPEN SOURCE LICENSE
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to IBK at info@ibk-software.ch.

!include ..\location

TARGET     = ZOracleI
TARGETLIB  =
SRCDIR     = $(SRCROOT)\Oracle
TARGETS    = $(BINDIR)\$(TARGET).dll
TARGETDIRS = $(BINDIR)
LIB        = $(ORACLE)\lib;$(LIB)
LIBRARIES  = ora7o32.lib
CLEANUPS   = 
CDEFS      =
LDEFS      =  
OBJECTS    = ZOracle.obj
INCLUDE    = $(ORACLE)\include;$(INCLUDE)
INCLUDES   = $(SRCDIR)\ZOracle.hpp
  
!include ..\makelib
